public class BusinessCentralAccount {
    public String number_X; //To be renamed to number before sendign to BC.
    public String name;
    public String type;
    public String code;	
    public Boolean isLive;
    public String serviceStatus;
    public String billToCustomerNumber;
    public String bidNumber;
    public String managerName;
    public String creditControllerName;
    public String addressLine1;
    public String addressLine2;
    public String city;
    public String country;
    public String postalCode;
    public String paymentTermsCode;
    public String accountTitle;
    public String bankAccountNumber;
    public String bankSortCode;
    public String paymentMethodCode;
    public String currencyCode;
    public String branch;
}