public without sharing class DeliveryPackage {

	public static final String STATUS_NEW = 'New';
	public static final String STATUS_ERROR = 'Error';
	public static final String STATUS_RETRY = 'Retry';
	public static final String STATUS_ADVISED = 'Advised';
	public static final String STATUS_LABELLED = 'Labelled';
	public static final String STATUS_LOCK = 'Lock';
    public static final String STATUS_PACKAGED = 'Packaged';
    public static final String STATUS_IN_PROGRESS = 'In Progress';
	public static final String STATUS_CANCEL_REQUEST = 'Request Cancellation';
	public static final String STATUS_CANCELLED = 'Cancelled';
	public static final String STATUS_REDELIVER = 'Redeliver';
	public static final String STATUS_DELIVERED = 'Delivered';
}